# Generated by Django 4.2.3 on 2023-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pen_count', models.IntegerField()),
                ('Eraser_count', models.IntegerField()),
                ('Notebook_count', models.IntegerField()),
                ('Stapler_count', models.IntegerField()),
                ('Calculator_count', models.IntegerField()),
            ],
        ),
    ]
