# Generated by Django 4.2.3 on 2023-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Calculator_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Eraser_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Notebook_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Pen_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Stapler_count',
            field=models.IntegerField(null=True),
        ),
    ]
